"""add application model

Revision ID: 8e632789a517
Revises: 010e5e8531fe
Create Date: 2026-08-27 13:55:53.293487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e632789a517'
down_revision: Union[str, Sequence[str], None] = '010e5e8531fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('application_id', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('package_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('install_state', sa.String(length=50), nullable=False),
    sa.Column('launch_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('store_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index(op.f('ix_applications_node_id'), 'applications', ['node_id'], unique=False)
    op.create_index(op.f('ix_applications_package_id'), 'applications', ['package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_package_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_node_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
