"""add permission model

Revision ID: 9a068fc1bcac
Revises: 9e5d9098e028
Create Date: 2026-08-27 13:58:50.095438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a068fc1bcac'
down_revision: Union[str, Sequence[str], None] = '9e5d9098e028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permission_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('capability', sa.String(length=255), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('confirmation_required', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_index(op.f('ix_permissions_capability'), 'permissions', ['capability'], unique=False)
    op.create_index(op.f('ix_permissions_subject'), 'permissions', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_subject'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_capability'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
