"""add task model

Revision ID: d50ed286d0ed
Revises: 9a068fc1bcac
Create Date: 2026-08-27 14:00:14.684740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd50ed286d0ed'
down_revision: Union[str, Sequence[str], None] = '9a068fc1bcac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('parent_task_id', sa.String(length=255), nullable=True),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=255), nullable=True),
    sa.Column('target_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_agents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_state'), 'tasks', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_state'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
